#! /bin/sh

#systemctl --user start sxhkd.service
~/Scripts/sxhkd.sh
~/.fehbg &
~/Scripts/polybar.sh
picom &
#compton &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop II -l monocle

bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Timeshift-gtk state=floating

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
